site_name: malmstin
repo_url: https://github.com/loucerac/malmstin
site_url: https://loucerac.github.io/malmstin
site_description: "Unveiling the Druggable Landscape: A Multimodal Approach (MALMSTIN)"
site_author: Carlos Loucera
edit_uri: edit/main/docs/
repo_name: loucerac/malmstin
copyright: Maintained by <a href="https://loucerac.com">Florian</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
            setup_commands:
                - import sys
                - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/loucerac/malmstin
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/malmstin

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
